import { useMemo, useState } from 'react';
import { BadgeIndianRupee, MapPin, Package, Search, ShieldCheck, ShoppingBag, Sprout } from 'lucide-react';
import { getTranslation } from '../data/translations';
import { pesticideAdvisorData, purchaseOptions } from '../data/pesticideAdvisorData';
import { getScanHistory } from '../utils/scanStorage';

const PesticideSubsidyAdvisorPage = ({ currentLang }) => {
  const activeLang = currentLang === 'hi' ? 'hi' : 'en';
  const t = getTranslation(activeLang);
  const [searchTerm, setSearchTerm] = useState('');
  const latestScan = useMemo(() => getScanHistory()[0], []);
  const recommendations = pesticideAdvisorData[latestScan?.diseaseKey] || [];
  const matches = recommendations.filter((item) => item.name.toLowerCase().includes(searchTerm.trim().toLowerCase()));

  return <div className="py-12 bg-[#f6f8f5] min-h-screen"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-8">
    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><span className="text-xs font-bold text-emerald-800 bg-emerald-100 px-3 py-1 rounded-full">{t.nav.pesticideAdvisor}</span><h1 className="text-3xl font-extrabold text-slate-900 tracking-tight mt-2">{t.ui.pesticideAdvisorTitle}</h1><p className="text-slate-600 text-sm">{t.ui.pesticideAdvisorDescription}</p></div><div className="relative"><Search className="w-4 h-4 text-emerald-600 absolute left-3 top-3" /><input type="search" value={searchTerm} onChange={(event) => setSearchTerm(event.target.value)} placeholder={t.ui.searchPesticide} className="pl-9 pr-4 py-2.5 rounded-xl border border-emerald-200 bg-white text-sm focus:outline-none focus:ring-2 focus:ring-emerald-500 font-medium shadow-xs" /></div></div>
    <div className="bg-gradient-to-br from-emerald-900 to-green-950 text-white p-6 sm:p-8 rounded-3xl shadow-lg"><div className="flex items-start gap-4"><Sprout className="w-8 h-8 text-emerald-300 shrink-0 mt-1" /><div><p className="text-xs font-bold text-emerald-300 uppercase tracking-wider">{t.ui.latestDiagnosis}</p><h2 className="text-xl font-extrabold mt-1">{latestScan?.diseaseName || t.ui.noDiagnosis}</h2>{latestScan?.crop && <p className="text-sm text-emerald-100 mt-1">{t.ui.cropName}: {latestScan.crop}</p>}</div></div></div>
    {matches.length > 0 ? <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">{matches.map((pesticide) => <article key={pesticide.name} className="bg-white p-6 rounded-3xl border border-emerald-100 shadow-xs space-y-5"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold text-emerald-700 uppercase">{t.ui.recommendedPesticide}</p><h2 className="text-xl font-extrabold text-slate-900 mt-1">{pesticide.name}</h2></div><div className="w-11 h-11 rounded-2xl bg-emerald-50 text-emerald-700 flex items-center justify-center shrink-0"><ShieldCheck className="w-5 h-5" /></div></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-sm"><div className="rounded-2xl bg-amber-50 border border-amber-100 p-4"><BadgeIndianRupee className="w-4 h-4 text-amber-700 mb-1" /><p className="text-xs font-bold text-amber-900">{t.ui.approximatePrice}</p><p className="font-extrabold text-slate-900 mt-1">{pesticide.price}</p></div><div className="rounded-2xl bg-blue-50 border border-blue-100 p-4"><Package className="w-4 h-4 text-blue-700 mb-1" /><p className="text-xs font-bold text-blue-900">{t.ui.packSizes}</p><p className="font-semibold text-slate-800 mt-1">{pesticide.packSizes.join(', ')}</p></div></div><div className="rounded-2xl bg-emerald-50 border border-emerald-100 p-4 text-sm"><p className="font-bold text-emerald-900">{t.ui.subsidyInformation}</p><p className="text-emerald-800 mt-1">{pesticide.subsidy || t.ui.noSubsidy}</p>{pesticide.eligibility && <><p className="font-bold text-emerald-900 mt-3">{t.ui.eligibility}</p><p className="text-emerald-800 mt-1">{pesticide.eligibility}</p></>}</div></article>)}</div> : <div className="bg-white p-8 rounded-3xl border border-emerald-100 text-center text-slate-600">{searchTerm ? t.ui.noSearchResults : t.ui.noPesticideRecommendation}</div>}
    <section className="bg-white p-6 sm:p-8 rounded-3xl border border-emerald-100 shadow-xs"><div className="flex items-center gap-2 mb-5"><ShoppingBag className="w-5 h-5 text-emerald-700" /><h2 className="text-lg font-extrabold text-slate-900">{t.ui.whereToBuy}</h2></div><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">{purchaseOptions.map((option) => <div key={option.type} className="rounded-2xl bg-slate-50 border border-slate-100 p-4"><MapPin className="w-4 h-4 text-emerald-600 mb-2" /><p className="text-sm font-bold text-slate-900">{option.type}</p><p className="text-xs text-slate-600 mt-1">{option.detail}</p></div>)}</div></section>
  </div></div>;
};

export default PesticideSubsidyAdvisorPage;
